package com.walrusone.skywars.utilities;

import java.util.ArrayList;
import java.util.List;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.configuration.file.FileConfiguration;

public class Config {

	public boolean signJoinMode;
	public boolean pressurePlateJoin;
	public boolean playerNameScoreboard;
	public int minPercentPlayers;
	public boolean allowSpectating;
	public boolean useExternalEconomy;
	public boolean noFallDamage;
	public boolean noFallDamageLobby;
	public int pointsPerKill;
	public int pointsLostPerDeath;
	public int pointsLostPerLeave;
	public int pointsPerWin;
	public int vipMultiplier;
	public int preGameTimer;
	public boolean resetPreGameTimerOnJoin;
	public int maxMapSize;
	public int maxNumberOfGames;
	public boolean kitsEnabled;
	public boolean shopsEnabled;
	public int timeAfterGame;
	public int statsCommandCooldown;
	public boolean addScorePrefix;
	public boolean useExternalChat;
	public boolean opChestsEnabled;
	public boolean timeVoteEnabled;
	public boolean jumpVoteEnabled;
	public boolean weatherVoteEnabled;
	public int lightningStrikeChance;
	public boolean colorGlassEnabled;
	public boolean particlesEnabled;
	public boolean trailEffectsEnabled;
	public boolean lobbyMenuEnabled;
	public boolean optionsMenuEnabled;
	public boolean purchaseColorGlassEnabled;
	public boolean purchaseParticlesEnabled;
	public boolean purchaseTrailEffectsEnabled;
	public boolean purchasePermanentKitsEnabled;
	public int highJumpValue;
	public int superJumpValue;
	public int godJumpValue;
	public boolean spectateShopEnabled;
	public boolean enableLogFilter;
	public boolean lobbyScoreBoardEnabled;
	public boolean disableWinBroadcast;
	public boolean clearInventoryOnJoin;
	public boolean clearXPOnJoin;
	public boolean clearPotionEffectsOnJoin;
	public String signJoinMaterial;
	public boolean giveSpectateItem;
	public int spectateItemSlot;
	public boolean giveLobbyMenuItem;
	public int lobbyMenuItemSlot;
	public boolean giveJoinItem;
	public int joinItemSlot;
	public String lobbyMenuItem; //Maybe turn these into items stacks in this class.
	public String spectateItem;
	public String joinItem;
	public String exitGameItem;
	public String kitMenuItem;
	public String kitPermMenuItem;
	public String specStoreItem;
	public String opChestMenuItem;
	public String timeMenuItem;
	public String weatherMenuItem;
	public String jumpMenuItem;
	public String particleMenuItem;
	public String trailEffectMenuItem;
	public String optionsItem;
	public String glassMenuItem;  //Ends here for itemstacks
	public String playerJoinLobby;
	public String playerLeaveLobby;
	public String playerDeath;
	public String playerWin;
	public String opChestVote;
	public String timeVote;
	public String weatherVote;
	public String jumpVote;
	public Location spawn;
	public List<String> commandWhitelist;
	public List<String> spectatorWhitelist;
	public boolean SQLenabled;
	public int SQLsaveInterval;
	public String SQLhostname;
	public int SQLport;
	public String SQLdatabase;
	public String SQLusername;
	public String SQLpassword;
	public boolean resaveDefaultMaps;
	public boolean BNGenabled;
	public String BNGbungeeServerName;
	public String BNGlobbyServer;

	public Config(FileConfiguration con) {
		signJoinMode = con.getBoolean("signJoinMode");
		pressurePlateJoin = con.getBoolean("pressurePlateJoin");
		playerNameScoreboard = con.getBoolean("gameVariables.playerNameScoreboard");
		minPercentPlayers = con.getInt("gameVariables.minPercentPlayers");
		allowSpectating = con.getBoolean("gameVariables.allowSpectating");
		useExternalEconomy = con.getBoolean("gameVariables.useExternalEconomy");
		noFallDamage = con.getBoolean("gameVariables.noFallDamage");
		noFallDamageLobby = con.getBoolean("gameVariables.noFallDamageLobby");
		pointsPerKill = con.getInt("gameVariables.pointsPerKill");
		pointsLostPerDeath = con.getInt("gameVariables.pointsLostPerDeath");
		pointsLostPerLeave = con.getInt("gameVariables.pointsLostPerLeave");
		pointsPerWin = con.getInt("gameVariables.pointsPerWin");
		vipMultiplier = con.getInt("gameVariables.vipMulitplier");
		preGameTimer = con.getInt("gameVariables.preGameTimer");
		resetPreGameTimerOnJoin = con.getBoolean("gameVariables.resetPreGameTimerOnJoin");
		maxMapSize = con.getInt("gameVariables.maxMapSize");
		maxNumberOfGames = con.getInt("gameVariables.maxNumberOfGames");
		kitsEnabled = con.getBoolean("gameVariables.kitsEnabled");
		shopsEnabled = con.getBoolean("gameVariables.shopsEnabled");
		timeAfterGame = con.getInt("gameVariables.timeAfterGame");
		statsCommandCooldown = con.getInt("gameVariables.statsCommandCooldown");
		addScorePrefix = con.getBoolean("gameVariables.addScorePrefix");
		useExternalChat = con.getBoolean("gameVariables.useExteralChat");
		opChestsEnabled = con.getBoolean("gameVariables.opChestsEnabled");
		timeVoteEnabled = con.getBoolean("gameVariables.timeVoteEnabled");
		jumpVoteEnabled = con.getBoolean("gameVariables.jumpVoteEnabled");
		weatherVoteEnabled = con.getBoolean("gameVariables.weatherVoteEnabled");
		lightningStrikeChance = con.getInt("gameVariables.lightningStrikeChance");
		colorGlassEnabled = con.getBoolean("gameVariables.colorGlassEnabled");
		particlesEnabled = con.getBoolean("gameVariables.particlesEnabled");
		trailEffectsEnabled = con.getBoolean("gameVariables.trailEffectsEnabled");
		lobbyMenuEnabled = con.getBoolean("gameVariables.lobbyMenuEnabled");
		optionsMenuEnabled = con.getBoolean("gameVariables.optionsMenuEnabled");
		purchaseColorGlassEnabled = con.getBoolean("gameVariables.purchaseColorGlassEnabled");
		purchaseParticlesEnabled = con.getBoolean("gameVariables.purchaseParticlesEnabled");
		purchaseTrailEffectsEnabled = con.getBoolean("gameVariables.purchaseTrailEffectsEnabled");
		purchasePermanentKitsEnabled = con.getBoolean("gameVariables.purchasePermanentKitsEnabled");
		highJumpValue = con.getInt("gameVariables.highJumpValue");
		superJumpValue = con.getInt("gameVariables.superJumpValue");
		godJumpValue = con.getInt("gameVariables.godJumpValue");
		spectateShopEnabled = con.getBoolean("gameVariables.spectateShopEnabled");
		enableLogFilter = con.getBoolean("gameVariables.enabledLogFilter");
		lobbyScoreBoardEnabled = con.getBoolean("gameVariables.lobbyScoreBoardEnabled");
		disableWinBroadcast = con.getBoolean("gameVariables.disabledWinBroadcast");
		clearInventoryOnJoin = con.getBoolean("gameVariables.clearInventoryOnJoin");
		clearXPOnJoin = con.getBoolean("gameVariables.clearXPOnJoin");
		clearPotionEffectsOnJoin = con.getBoolean("gameVariables.clearPotionEffectsOnJoin");
		signJoinMaterial = con.getString("gameVariables.signJoinMaterial");
		giveSpectateItem = con.getBoolean("gameItems.giveSpectateItem");
		spectateItemSlot = con.getInt("gameItems.spectateItemSlot");
		giveLobbyMenuItem = con.getBoolean("gameItems.giveLobbyMenuItem");
		lobbyMenuItemSlot = con.getInt("gameItems.lobbyMenuItemSlot");
		giveJoinItem = con.getBoolean("gameItems.giveJoinItem");
		joinItemSlot = con.getInt("gameItems.joinItemSlot");
		lobbyMenuItem = con.getString("gameItems.lobbyMenuItem");
		spectateItem = con.getString("gameItems.spectateItem");
		joinItem = con.getString("gameItems.joinItem");
		exitGameItem = con.getString("gameItems.exitGameItem");
		kitMenuItem = con.getString("gameItems.kitMenuItem");
		kitPermMenuItem = con.getString("gameItems.kitPermMenuItem");
		specStoreItem = con.getString("gameItems.specStoreItem");
		opChestMenuItem = con.getString("gameItems.opChestMenuItem");
		timeMenuItem = con.getString("gameItems.timeMenuItem");
		weatherMenuItem = con.getString("gameItems.weatherMenuItem");
		jumpMenuItem = con.getString("gameItems.jumpMenuItem");
		particleMenuItem = con.getString("gameItems.particleMenuItem");
		trailEffectMenuItem = con.getString("gameItems.trailEffectMenuItem");
		optionsItem = con.getString("gameItems.optionsItem");
		glassMenuItem = con.getString("gameItems.glassMenuItem");
		playerJoinLobby = con.getString("gameSounds.playerJoinLobby");
		playerLeaveLobby = con.getString("gameSounds.playerLeaveLobby");
		playerDeath = con.getString("gameSounds.playerDeath");
		playerWin = con.getString("gameSounds.playerWin");
		opChestVote = con.getString("gameSounds.opChestVote");
		timeVote = con.getString("gameSounds.timeVote");
		weatherVote = con.getString("gameSounds.weatherVote");
		jumpVote = con.getString("gameSounds.jumpVote");
		World w = Bukkit.getWorld(con.getString("spawn.world"));
		float yaw = (float) con.get("spawn.yaw");
		float pitch = (float) con.get("spawn.pitch");
		Location l = new Location(w, con.getDouble("spawn.x"), con.getDouble("spawn.y"), con.getDouble("spawn.z"), yaw,  pitch);
		spawn = l;
		List<String> cmdList = new ArrayList<String>();
		for (String s: con.getStringList("commandWhitelist")) {
			cmdList.add(s);
		}
		commandWhitelist = cmdList;
		List<String> specList = new ArrayList<String>();
		for (String s: con.getStringList("spectatorWhitelist")) {
			specList.add(s);
		}
		spectatorWhitelist = specList;
		SQLenabled = con.getBoolean("sqldatabase.enabled");
		SQLsaveInterval = con.getInt("sqldatabase.saveInterval");
		SQLhostname = con.getString("sqldatabase.hostname");
		SQLport = con.getInt("sqldatabase.port");
		SQLdatabase = con.getString("sqldatabase.database");
		SQLusername = con.getString("sqldatabase.username");
		SQLpassword = con.getString("sqldatabase.password");
		resaveDefaultMaps = con.getBoolean("resaveDefaultMaps");
		BNGenabled = con.getBoolean("bungeeMode.enabled");
		BNGbungeeServerName = con.getString("bungeeMode.bungeeServerName");
		BNGlobbyServer = con.getString("bungeeMode.lobbyServer");
	}

}
